server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  #- url: http://loki:3100/loki/api/v1/push
  - url: http://host.docker.internal:3100/loki/api/v1/push

scrape_configs:
  - job_name: 'uois'
    static_configs:
      - targets:
          - localhost
        labels:
          job: uois
          __path__: /logs/*.log
    relabel_configs:
      - source_labels: [__path__]
        regex: .*/([a-zA-Z0-9_-]+)\.log
        target_label: service
