global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'monitoring@example.com'
  smtp_auth_username: 'monitoring@example.com'
  smtp_auth_password: 'your-smtp-password'
  smtp_require_tls: true

route:
  group_by: ['alertname', 'service']
  group_wait: 30s
  group_interval: 10m
  repeat_interval: 1h
  receiver: 'default-receiver'

  # routes:
  #   - match:
  #       severity: critical
  #     receiver: 'email-notification'
  #     continue: true

  #   - match:
  #       severity: warning
  #     receiver: 'slack-notification'

receivers:
  - name: 'default-receiver'
    email_configs:
      - to: 'default@example.com'

#   - name: 'email-notification'
#     email_configs:
#       - to: 'oncall@example.com'
#         send_resolved: true

#   - name: 'slack-notification'
#     slack_configs:
#       - api_url: 'https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX'
#         channel: '#alerts'
#         send_resolved: true
#         title: '{{ .CommonLabels.alertname }} ({{ .CommonLabels.severity }})'
#         text: >-
#           {{ range .Alerts }}
#           *Alert:* {{ .Annotations.summary }}
#           *Description:* {{ .Annotations.description }}
#           *Time:* {{ .StartsAt }}
#           {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service']
