global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'


# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9070']

  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://frontend:8000
          - http://gql_forms:8000/gql 
          - http://gql_ug:8000/gql
          - http://gql_granting:8000/gql
          - http://gql_facilities:8000/gql
          - http://gql_events:8000/gql
          - http://gql_publications:8000/gql
          - http://gql_projects:8000/gql
          - http://gql_lessons:8000/gql
          - http://gql_surveys:8000/gql
          - http://gql_externalids:8000/gql
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

  # - job_name: 'graphql_exporter'
  #   static_configs:
  #     - targets: ['graphql_exporter:9199']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
      
  - job_name: 'uois'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      #- targets: ['127.0.0.1:8000'] #down
      # private ip #down
      #- targets: ['localhost:8000'] #down
      #- targets: ['host.docker.internal:8000']
      #add new targets here
      - targets: ['frontend:8000']
      - targets: ['gql_forms:8000']

      #localhost:8000 Get "http://localhost:8000/metrics": dial tcp [::1]:8000: connect: connection refused
      #https://stackoverflow.com/questions/54397463/getting-error-get-http-localhost9443-metrics-dial-tcp-127-0-0-19443-conne
      

# remote_write:
#   - url: 'http://prometheus_server:9090/api/v1/write'

remote_write:
  # The path depends on the environment being executed
  #- url: 'http://your-remote-write-target/endpoint
  - url: 'http://host.docker.internal:9090/api/v1/write'

scrape_configs:
  - job_name: 'uois'
    static_configs:
#add targets here
      - targets: ['frontend:8000']
remote_write:
  - url: 'http://prometheus-server:9090/api/v1/write'
